"""
ReplyGrader — keyword + heuristic quality grader for generated replies.

Design goals:
  - Deterministic: no LLM calls; pure string matching.
  - Partial credit: each keyword matched adds proportional reward.
  - Length penalty: empty or single-word replies score 0.
  - Relevance bonus: reply must mention at least one noun from the email body.

Scoring breakdown (all normalised to [0, 1]):
  keyword_score    = matched_keywords / total_keywords   (0.70 weight)
  relevance_score  = 1 if any body noun appears in reply, else 0  (0.20 weight)
  length_score     = min(1, word_count / 15)             (0.10 weight)

Final = 0.70 * keyword + 0.20 * relevance + 0.10 * length
"""

from __future__ import annotations
import re


class ReplyGrader:
    # Minimum words for a reply to be considered non-trivial
    MIN_WORDS = 15

    # Common English stop-words to exclude from relevance check
    STOP_WORDS = {
        "the", "a", "an", "is", "it", "in", "on", "at", "to", "for",
        "of", "and", "or", "but", "with", "this", "that", "was", "be",
        "have", "had", "has", "are", "i", "you", "we", "he", "she",
        "they", "my", "your", "our", "their", "its",
    }

    def score(
        self,
        reply_text: str,
        expected_keywords: list[str],
        email_body: str,
    ) -> tuple[float, dict]:
        """
        Parameters
        ----------
        reply_text        : The reply generated by the agent.
        expected_keywords : Ground-truth keyword list for this email.
        email_body        : Original email body (for relevance check).

        Returns
        -------
        (reward ∈ [0,1], info_dict)
        """
        reply_lower = reply_text.lower()
        word_count  = len(reply_text.split())

        # -- 1. Keyword score -----------------------------------------------
        if expected_keywords:
            matched = [kw for kw in expected_keywords
                       if kw.lower() in reply_lower]
            kw_score = len(matched) / len(expected_keywords)
        else:
            matched  = []
            kw_score = 1.0   # No keywords specified → perfect by default

        # -- 2. Relevance score ---------------------------------------------
        body_tokens = set(re.findall(r"\b\w{4,}\b", email_body.lower()))
        body_tokens -= self.STOP_WORDS
        reply_tokens = set(re.findall(r"\b\w{4,}\b", reply_lower))
        overlap = body_tokens & reply_tokens
        relevance_score = 1.0 if overlap else 0.0

        # -- 3. Length score ------------------------------------------------
        length_score = min(1.0, word_count / self.MIN_WORDS)

        # -- Weighted final -------------------------------------------------
        final = round(
            0.70 * kw_score +
            0.20 * relevance_score +
            0.10 * length_score,
            4,
        )

        return final, {
            "grader":           "reply",
            "keyword_score":    round(kw_score, 4),
            "relevance_score":  relevance_score,
            "length_score":     round(length_score, 4),
            "matched_keywords": matched,
            "word_count":       word_count,
            "reward":           final,
        }
